myproject1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('', include('board.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('news/', include('news.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from .views import NewsList, NewsSearch, NewsDetailView, NewsCreateView, NewsUpdateView, NewsDeleteView # импортируем наше представление
from django.contrib.auth.views import LoginView, LogoutView
from .views import BaseRegisterView
from .views import upgrade_me, Subscribers
from django.views.decorators.cache import cache_page

urlpatterns = [
    # path — означает путь. В данном случае путь ко всем товарам у нас останется пустым, позже станет ясно почему
    path('', NewsList.as_view()),
    path('search', NewsSearch.as_view()),
    path('<int:pk>', NewsDetailView.as_view(), name='news'),
    path('add/', NewsCreateView.as_view(), name='news_create'),
    path('<int:pk>/edit/', NewsUpdateView.as_view(), name='news_update'),
    path('<int:pk>/delete/', NewsDeleteView.as_view(), name='news_delete'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('signup/', BaseRegisterView.as_view(template_name='signup.html'), name='signup'),
    path('upgrade/', upgrade_me, name='upgrade'),
    path('category/', Subscribers),
]

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.core.cache import cache


class Author(models.Model):
    account = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.account}'

    def update_rating(self):
        postrat = self.post_set.all().aggregate(postRating=Sum('rating'))
        prat = 0
        prat += postrat.get('postRating')
        comrat = self.account.comment_set.all().aggregate(commentRating=Sum('rating'))
        crat = 0
        crat += comrat.get('commentRating')
        self.ratingAuthor = prat * 3 + crat
        self.save()


class Category(models.Model):
    categoryName = models.CharField(max_length=255, unique=True)
    subscribers = models.ManyToManyField(User, through="AuthorCategory")

    def __str__(self):
        return f'{self.categoryName}'

class AuthorCategory(models.Model):
    in_user = models.ForeignKey(User, on_delete=models.CASCADE)
    in_category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Post(models.Model):
    authorArticle = models.ForeignKey(Author, on_delete=models.CASCADE)
    article = 'AR'
    news = 'NW'

    TEXT = [
        (article, 'Статья'),
        (news, 'Новость')
    ]
    textContent = models.CharField(max_length=2,
                                   choices=TEXT,
                                   default=news)
    creationTime = models.DateTimeField(auto_now_add=True)
    textCategory = models.ManyToManyField(Category, through='PostCategory')
    header = models.CharField(max_length=255)
    postText = models.TextField()
    rating = models.IntegerField(default=1)

    def like(self):
        self.rating += 1
        self.save()
        return self.rating

    def dislike(self):
        if self.rating:
            self.rating -= 1
            self.save()
        return self.rating

    def preview(self):
        return self.postText[0:123] + '...'

    def __str__(self):
        return f'{self.header} {self.postText}'

    def get_absolute_url(self):  # добавим абсолютный путь, чтобы после создания нас перебрасывало на страницу с товаром
        return f'/news/{self.id}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        cache.delete(f'news-{self.pk}')



class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    userComment = models.ForeignKey(User, on_delete=models.CASCADE)
    commentText = models.TextField()
    commentTime = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        if self.rating:
            self.rating -= 1
            self.save()

class BaseRegisterForm(UserCreationForm):
    email = forms.EmailField(label = "Email")
    first_name = forms.CharField(label = "Имя")
    last_name = forms.CharField(label = "Фамилия")

    class Meta:
        model = User
        fields = ("username",
                  "first_name",
                  "last_name",
                  "email",
                  "password1",
                  "password2", )

news/forms.py
from django.forms import ModelForm, BooleanField
from .models import Post, Category, PostCategory
from allauth.account.forms import SignupForm
from django.contrib.auth.models import Group

# Создаём модельную форму
class NewsForm(ModelForm):
    class Meta:
        model = Post
        fields = ['header', 'textCategory', 'authorArticle', 'postText']


class BasicSignupForm(SignupForm):

    def save(self, request):
        user = super(BasicSignupForm, self).save(request)
        basic_group = Group.objects.get(name='common')
        basic_group.user_set.add(user)
        return user

news/views.py
from django.shortcuts import render, reverse, redirect
from django.views.generic import ListView, UpdateView, CreateView, DetailView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post,Category
from .filters import NewsFilter
from .forms import NewsForm
from django.contrib.auth.models import User
from .models import BaseRegisterForm
from django.shortcuts import redirect
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.mail import send_mail
from django.core.cache import cache


class NewsList(ListView):
	model = Post
	template_name = 'news_list.html'  # указываем имя шаблона, в котором будет лежать HTML, в нём будут все инструкции о том, как именно пользователю должны вывестись наши объекты
	context_object_name = 'newsall'
	queryset = Post.objects.order_by('-creationTime')
	paginate_by = 5

	def post(self, request, *args, **kwargs):
		category_id = request.POST['cat']
		re = Post.objects.filter(textCategory=category_id)
		ca = Category.objects.all()
		cat_name = request.POST['btn']

		return render(request, 'news_list.html', {'posts': re, 'categ': ca, 'cat_name': cat_name})

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['categ'] = Category.objects.all()
		return context


class NewsSearch(ListView):
	model = Post
	template_name = 'search.html'  # указываем имя шаблона, в котором будет лежать HTML, в нём будут все инструкции о том, как именно пользователю должны вывестись наши объекты
	context_object_name = 'newsSearch'
	queryset = Post.objects.order_by('-creationTime')
	paginate_by = 1

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['filter'] = NewsFilter(self.request.GET,
		queryset=self.get_queryset())  # вписываем наш фильтр в контекст
		return context


# дженерик для получения деталей о товаре
class NewsDetailView(DetailView):
	template_name = 'news.html'
	context_object_name = 'news'
	queryset = Post.objects.all()

	def get_object(self, *args, **kwargs):
		obj = cache.get(f'news-{self.kwargs["pk"]}',
						None)
		if not obj:
			obj = super().get_object(queryset=self.queryset)
			cache.set(f'news-{self.kwargs["pk"]}', obj)
		return obj



# дженерик для создания объекта. Надо указать только имя шаблона и класс формы который мы написали в прошлом юните. Остальное он сделает за вас
class NewsCreateView(PermissionRequiredMixin, CreateView):
	permission_required = ('news.add_post',)
	template_name = 'news_create.html'
	form_class = NewsForm


# дженерик для редактирования объекта
class NewsUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
	permission_required = ('news.change_post',)
	template_name = 'news_create.html'
	form_class = NewsForm

	def get_object(self, **kwargs):
		id = self.kwargs.get('pk')
		return Post.objects.get(pk=id)


# дженерик для удаления товара
class NewsDeleteView(DeleteView):
	template_name = 'news_delete.html'
	queryset = Post.objects.all()
	success_url = '/news/'

class BaseRegisterView(CreateView):
	model = User
	form_class = BaseRegisterForm
	success_url = '/'

@login_required
def upgrade_me(request):
	user = request.user
	premium_group = Group.objects.get(name='authors')
	if not request.user.groups.filter(name='authors').exists():
		premium_group.user_set.add(user)
	return redirect('/')

@login_required
def Subscribers(request):
	user = request.user
	if request.POST['sub']:
		subs = request.POST['sub']
		category_sub = Category.objects.get(categoryName=subs)
		category_sub.subscribers.add(user.id)
		category_sub.save()
	return redirect('/')

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block head_title %}{% endblock head_title %}</title>
    </head>
    <body>

        {% load cache %} <!-- Загружаем кэширование -->
        {% cache 30 header %} <!-- Кэшируем отдельный блок на 30 секунд -->
        {% block header %}
        {% endblock header %}
        {% endcache %}

        {% block body %}
        {% block content %}
        {% endblock content %}
        {% endblock body %}
        {% block extra_body %}
        {% endblock extra_body %}
    </body>
</html>

templates/create_post.html
{% extends 'default.html' %}
{% load bootstrap4 %}
{% block title %}Create{% endblock title %}
{% load static %}
<!--<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>-->
<!--<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>-->
<!--<script src="{{STATIC_URL}}ckeditor/ckeditor.js"></script>-->
<!--<script src="//cdn.ckeditor.com/4.17.1/full/ckeditor.js"></script>-->
<!--<script>-->
<!--  CKEDITOR.replace( '.richtexteditor' );-->
<!--</script>-->
{% block content %}
    <br>
    <h3>Новое объявление</h3><br>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
		<input class="btn btn-dark" type="submit" value="Сохранить">
	</form><br>
    <input type=button value="Назад" class="btn btn-dark" onClick="javascript:history.go(-1);">
{% endblock content %}

templates/default.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Flatpages</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'index' %}">MMORPG</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'index' %}">Главная</a></li>
                        <li class="nav-item"><a class="nav-link" href="/contacts/">Контакты</a></li>
 			<li class="nav-item"><a class="nav-link" href="/about/">О нас</a></li>
			<li class="nav-item"><a class="nav-link" href="/price/">Цены</a></li>
            <li class="nav-item"><a class="nav-link" href="/news/">Новости</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'index' %}">Доска объявлений</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'responses' %}">Отклики</a></li>
                        {% if user.is_authenticated %}
          <li class="nav-item">
              <a class="nav-link" href="{% url 'account_profile' %}">Мой профиль</a>
          </li>
          {% else %}
          <li class="nav-item">
              <a class="nav-link" href="{% url 'account_login' %}">Авторизация</a>
          </li>
          {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        <div class="container">
            <div class="text-center mt-5">
                {% block content %}
       		{{ flatpage.content }}
       		{% endblock content %}
            </div>
        </div>

    <!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.slim.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    </body>
</html>

templates/index.html
{% extends 'default.html' %}
{% load bootstrap4 %}
{% block title %}Ads{% endblock title %}

{% block content %}
<img src="/static/img/header.jpg" class="img-fluid" alt="...">
     <h3>Доска объявлений</h3>
    <br><br>
    {% if posts %}
        {% for post in posts %}
            <a href="/post/{{ post.id }}" style="font-size: 20px;"><b>{{ post.title }}</b></a><br>
            <span style="font-size: 12px;"><b>Автор:  {{ post.author }} |
                Дата публикации: {{ post.dateCreation|date:'d.M.Y' }} г.</b></span><br><br>



        {% endfor %}
    {% else %}
        <br><br>
        <h2>Публикаций нет!</h2>
    {% endif %}

    {% if user.is_authenticated %}
        <br><br><br>
        <a class="btn btn-dark" href="{% url 'create_ad' %}" role="button">Добавить новое объявление</a>

    {% endif %}
{% endblock content %}

templates/login.html
{% extends "news.html" %}

{% block content %}
<h2> Войти в систему </h2>
<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="Войти">
</form>
<button> <a href="/news/signup"> Регистрация </a></button>
{% endblock %}

templates/news.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
News
{% endblock title %}

{% block content %}
   
 
   
    {% if news %}
        <table>
            <tr>
                <td>
                    Заголовок
                </td>
				<td>
                    Автор
                </td>
                <td>
                    Дата создания
                </td>
                <td>
                    Текст статьи
                </td>
               
            </tr>
        
            <tr>
                <td>
                    {{ news.header}}
					<a href="{% url 'news_delete' news.id %}"><u> Удалить </u></a>
	                <a href="{% url 'news_update' news.id %}"><u> Редактировать </u></a>
                </td>
				<td>
                    {{ news.authorArticle.account}}
                </td>
                <td>
		   {{ news.creationTime.day}}-{{ news.creationTime.month}}-{{news.creationTime.year}} {{ news.creationTime.hour}}:{{ news.creationTime.minute}}
                </td>
                <td>
                    {{ news.postText}}
                </td>
            </tr>
        </table>
    {% else %}
        <h2>Новостей нет!</h2>
    {% endif %}
{% endblock content %}

templates/news_create.html
{% extends 'flatpages/default.html' %}
 
{% block title %} News list {% endblock title %}
 
{% block content %}
<h3>Форма добавления новостей</h3>
<form method="POST">
    {% csrf_token %} 
    {{ form }} <!-- Теперь нам нужна только готовая форма и кнопка -->
    <input type="submit" value="Добавить новость">
</form>
{% endblock content %}

templates/news_delete.html
{% extends 'flatpages/default.html' %}

{% block title %} News list {% endblock title %}

{% block content %}
<h2>Вы действительно хотите удалить данную новость?</h2>
<table>
    <thead>
        <th>
            Header
        </th>
		<th>
            Author
        </th>
        <th>
            Creation time
        </th>
        <th>
            Post Text
        </th>
    </thead>
    <tr>
        <td>
            {{ news.header|title }}
        </td>
		<td>
            {{ news.authorArticle.account|title }}
        </td>
        <td>
            {{ news.creationTime|title }}
        </td>
        <td>
             {{ news.postText}}
        </td>
    </tr>
</table>

<form method="POST">
    {% csrf_token %}
    <input type="submit" value="подтвердить"></form>
{% endblock content %}

templates/newsall.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
News
{% endblock title %}

{% block content %}
    <h1>Всего {{ newsall|length }} новости  </h1>
    <hr>
    {% if newsall %}
        <table>
            <tr>
                <td>
                    Заголовок
                </td>
                <td>
                    Дата
                </td>
                <td>
                    Текст статьи
                </td>
               
            </tr>
        {% for article in newsall %}
            <tr>
                <td>
                    {{ article.header|censor}}
                </td>
                <td>
		    {{ article.creationTime}}
                </td>
                <td>
                    {{ article.description|truncatechars:50|censor}}
                </td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <h2>Новостей нет!</h2>
    {% endif %}
{% endblock content %}

templates/post_item.html
{% extends 'default.html' %}

{% block title %}Ad{% endblock title %}

{% block content %}
    <br><br>
    {% autoescape off %}
    <h2>{{ post.title }}</h2><br>
    <span>{{ post.text }}<br></span>
    {% endautoescape %}
    <hr>
    <span>Автор: {{ post.author }}</span>
    <span>| Категория: {{ post.get_category_display }}</span>
    <span>| Дата публикации: {{ post.dateCreation|date:'d-M-Y f' }}</span>

    <br><br>

    <a class="btn btn-dark" href="{% url 'index' %}" role="button">Закрыть</a>
    <a class="btn btn-dark" href="/post/{{ post.id }}/edit" role="button">Редактировать</a>
    <a class="btn btn-dark" href="/post/{{ post.id }}/delete" role="button">Удалить</a>

    {% if user.is_authenticated %}
    <br><br>
        {% if respond == "Откликнулся" %}
            <a style="color:red">Вы откликнулись на это объявление.</a><br>
            <a href="{% url 'responses' %}">Посмотреть свои отклики</a>
        {% elif respond == "Мое_объявление" %}
            <a style="color:red">Вы не можете откликнуться на свое объявление.</a><br>
        {% else %}
            <a class="btn btn-dark" href="/respond/{{ post.id }}" role="button">Откликнуться</a>
        {% endif %}
    {% endif %}
    <br><br>
{% endblock content %}

templates/respond.html
{% extends 'default.html' %}
{% load bootstrap4 %}
{% block title %}Respond{% endblock title %}
{% load static %}

{% block content %}
    <br>
    <h3>Текст отклика:</h3><br>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{% bootstrap_form form layout='horizontal' %}
	<br>
		<input class="btn btn-dark" type="submit" value="Сохранить">
	</form><br>
    <input type=button value="Назад" class="btn btn-dark" onClick="javascript:history.go(-1);">
{% endblock content %}

templates/responses.html
{% extends 'default.html' %}
{% load bootstrap4 %}
{% block title %}Responses{% endblock title %}

{% block content %}
    <br>
    <h3>Фильтр откликов на мои объявления:</h3><br>
	<form method="POST">
		{% csrf_token %}
        {{ form }}
		<input class="btn btn-dark" type="submit" value="Показать">
	</form><br>
    {% if title %}
        <h3>Oтклики на мое объявление</h3>
        <a href="/post/{{ response_post_id }}" style="font-size: 20px;"><b>{{ title }}:</b></a><br>
        {% if filter_responses %}
            {% for response in filter_responses %}
                <a><b>Отклик: </b></a>{{ response.text }}<br>
                <span style="font-size: 12px;"><b>Автор отклика: {{ response.author.username }} |
                    дата публикации отклика: {{ response.dateCreation|date:'d.M.Y' }} г.</b></span><br>
                {% if response.status == False %}
                    <a href="/response/accept/{{ response.id }}" style="font-size: 12px; color:green"><b>принять</b></a>
                    <a>&nbsp;&nbsp;&nbsp;</a>
                    <a href="/response/delete/{{ response.id }}" style="font-size: 12px; color:red"><b>удалить</b></a>
                {% else %}
                    <a style="font-size: 14px; color:green"><b>отклик принят</b></a>
                {% endif %}
                <br><br>
            {% endfor %}
        {% else %}
            <br>
            <h5>Откликов нет!</h5>
        {% endif %}
    {% else %}
        <h3>Oтклики на все мои объявления:</h3>
        {% if filter_responses %}
            {% for response in filter_responses %}
                <a><b>Объявление:</b></a>
                <a href="/post/{{ response.post_id }}" style="font-size: 20px;"><b>{{ response.post.title }}</b></a><br>
                <span style="font-size: 12px;"><b>Дата публикации объявления: {{ response.post.dateCreation|date:'d.M.Y' }} г.</b>
                </span><br>
                <a><b>Отклик: </b></a>{{ response.text }}<br>
                <span style="font-size: 12px;"><b>Автор отклика: {{ response.author.username }} |
                    дата публикации отклика: {{ response.dateCreation|date:'d.M.Y' }} г.</b></span><br>
                {% if response.status == False %}
                    <a href="/response/accept/{{ response.id }}" style="font-size: 12px; color:green"><b>принять</b></a>
                    <a>&nbsp;&nbsp;&nbsp;</a>
                    <a href="/response/delete/{{ response.id }}" style="font-size: 12px; color:red"><b>удалить</b></a>
                {% else %}
                    <a style="font-size: 14px; color:green"><b>отклик принят</b></a>
                {% endif %}
                <br><br>
            {% endfor %}
        {% else %}
            <h5>Откликов нет!</h5>
        {% endif %}
    {% endif %}
    <br><br>
    <h3>Мои отклики на объявления:</h3>
    {% if myresponses %}
        {% for response in myresponses %}
            <a><b>Объявление:</b></a>
            <a href="/post/{{ response.post_id }}" style="font-size: 20px;"><b>{{ response.post.title }}</b></a><br>
            <span style="font-size: 12px;"><b>Автор объявления:  {{ response.post.author.username }} |
                дата публикации объявления: {{ response.post.dateCreation|date:'d.M.Y' }} г.</b></span><br>
            <a><b>Мой отклик:</b></a>
            {{ response.text }}<br>
            <span style="font-size: 12px;"><b>Дата публикации отклика: {{ response.dateCreation|date:'d.M.Y' }} г.</b></span><br>
            {% if response.status == True %}
                <a style="font-size: 14px; color:green"><b>Автор объявления принял отклик!</b></a>
            {% else %}
                <a style="font-size: 14px; color:red"><b>Автор объявления пока не принял отклик!</b></a>
            {% endif %}
        <br><br>
        {% endfor %}
    {% else %}
        <h5>Откликов нет!</h5>
    {% endif %}
{% endblock content %}

templates/search.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
News
{% endblock title %}

{% block content %}
<form method="GET">
    {{ filter.form }}
    <input type="submit" value="Найти">
</form>
        <table>
            <tr>
                <td>
                    Заголовок 
                </td>
				<td>
                    Автор 
                </td>
                <td>
                    Дата создания 
                </td>
                <td>
                    Текст статьи 
                </td>
               
            </tr>
        {% for article in filter.qs %}
            <tr>
                <td>
                    {{ article.header}}
                </td>
				<td>
                    {{ article.authorArticle.account}}
                </td>
                <td>
					{{ article.creationTime}}
                </td>
                <td>
                    {{ article.postText}}
                </td>
            </tr>
        {% endfor %}
        </table>
  
<!-- Проверяем что поддерживается постраничный вывод -->
 

{% endblock content %}

templates/signup.html
{% extends "news.html" %}

{% block content %}
<h2> Войти в систему </h2>
<form method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Продолжить">
</form>
{% endblock %}